version: '3.4'

configs:
  mysql_init:
    file: ./init.sql


services:
  updaemon-db:
    image: mysql:5.7.37-debian
    configs:
      - source: mysql_init
        target: /var/opt/init.sql
    platform: linux/amd64
    user: "1000:50"
    command: --init-file /var/opt/init.sql
    volumes:
      - updaemon-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=updaemon
      - MYSQL_ROOT_PASSWORD=<root password>

  run-migrations:
    build:
      context: ./
      dockerfile: ./db/Dockerfile
    command: bash -c ". /opt/updaemon/wait-for updaemon-db:3306 -- /opt/venv/bin/python /opt/db/run_migrations.py --config /opt/db/updaemon.conf --dir /opt/db/migrations"
    depends_on:
      - updaemon-db
    volumes:
      - ./:/opt/updaemon

  updaemon:
    build: .
    command: bash -c "cron && tail -F /var/log/cron.log"
    image: debian:buster
    depends_on:
      - updaemon-db
      - run-migrations
    tmpfs:
      - /tmp
    volumes:
      - ./:/opt/updaemon

  web:
    build:
      context: ./
      dockerfile: ./web/Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./web:/opt/web
    environment:
      - UPDAEMON_CONFIG_FILE=/opt/updaemon.conf
      - FLASK_APP=.
      - FLASK_DEBUG=1

volumes:
  updaemon-data: {}

