services:
  updaemon-db:
    image: mysql:5.7.37-debian
    platform: linux/amd64
    user: "1000:50"
    volumes:
      - updaemon-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<root password>

  run-migrations:
    image: debian:stable
    command: bash -c ". /opt/updaemon/wait-for updaemon-db:3306 -- /opt/venv/bin/python /opt/updaemon/db/run_migrations.py --config updaemon.conf --dir /opt/updaemon/db/migrations"
    depends_on:
      - updaemon-db
    volumes:
      - ./:/opt/updaemon

  updaemon:
    build: .
    command: bash -c "cron && tail -F /var/log/cron.log"
    image: debian:stable
    depends_on:
      - updaemon-db
      - run-migrations
    tmpfs:
      - /tmp
    volumes:
      - ./:/opt/updaemon

  web:
    build:
      context: ./
      dockerfile: ./web/Dockerfile
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./web:/opt/web
    environment:
      - UPDAEMON_CONFIG_FILE=/opt/updaemon.conf
      - FLASK_APP=.
      - FLASK_DEBUG=1

volumes:
  updaemon-data: {}

